### ISSUE TITLE
TODO's for web-parameters & guards

### ISSUE THREAD

**Issue by ikbendewilliam** [ikbendewilliam/flutter_navigation_generator#16]
- [x] Add a way to redirect after login (after guard)
- [x] Add tests for guards
- [x] Add tests for unknown route
- [x] Fix issue with List<dynamic> is not List<String>
- [x] Add tests for types
- [x] Remove type for updateGuards method
- [x] Add default guards?
- [x] #12 
- [x] #1 
- [x]  Documentation

**Comment by ikbendewilliam** [comment]
V2 is released
